# Buildx multi-architecture Dockerfile pour une application FastAPI
# 
# docker buildx create --use # Crée et utilise un nouveau builder
# docker buildx build --platform linux/amd64,linux/arm64 -t fastapi-multiarch:latest -f Dockerfile.fastapi .
# docker run -d -p 80:80 fastapi-multiarch:latest
#
FROM python:3.11-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier le code source avec le requirements.txt
COPY app .

# Copier les dépendances et les installer
RUN pip install --no-cache-dir -r requirements.txt


# Lancer l'application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
